version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing requirements"
      - if [ -f requerments.txt ]; then pip install -r requerments.txt -t .; fi
  build:
    commands:
      - echo "Zipping lambda layers"
      - zip -r extractor_lambda.zip extractor_lambda.py
      - zip -r transformer_lambda.zip transformer_lambda.py
      - zip -r loader_lambda.zip loader_lambda.py
  post_build:
    commands:
      - echo "Build process completed"

artifacts:
  files:
    - extractor_lambda.zip
    - transformer_lambda.zip
    - loader_lambda.zip